//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACPModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class codingset
    {
        public int id { get; set; }
        public string codingsystem { get; set; }
        public string codedesignation { get; set; }
        public string publisher { get; set; }
        public string version { get; set; }
        public string domain { get; set; }
        public string filename { get; set; }
        public Nullable<bool> agreementrequest { get; set; }
        public Nullable<bool> ingenixrequest { get; set; }
        public Nullable<bool> cdtagreementrequest { get; set; }
        public string downloadmessageinstead { get; set; }
        public Nullable<System.DateTime> updatedate { get; set; }
        public Nullable<bool> isactive { get; set; }
        public string listname { get; set; }
    }
}
