//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACPModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("facility")]
    public partial class facility
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public facility()
        {
            this.clinician = new HashSet<clinician>();
            this.user = new HashSet<user>();
        }
    
        public int ID { get; set; }
        public string License { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public Nullable<byte> FacilityType { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<bool> CodingSet_IngenixRequested { get; set; }
        public Nullable<bool> CodingSet_AgreementSigned { get; set; }
        public Nullable<bool> CodingSet_CDTAgreementSigned { get; set; }
        public Nullable<System.DateTime> CodingSet_IngenixRequestDate { get; set; }
        public Nullable<bool> activated { get; set; }
        public Nullable<System.DateTime> activateDate { get; set; }
        public Nullable<bool> ToActivate { get; set; }
        public Nullable<int> ingenix_usersno { get; set; }
        public Nullable<bool> validated { get; set; }
        public Nullable<bool> demo { get; set; }
        public string license_eclaimlink { get; set; }
        public string license_dha { get; set; }
        public string ProviderType { get; set; }
        public string Source { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<clinician> clinician { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user> user { get; set; }
    }
}
