//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACPModel
{
    using MySql.Data.Entity;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    [DbConfigurationType(typeof(MySqlEFConfiguration))]
    public partial class eclaimlinkportalEntities : DbContext
    {
        public eclaimlinkportalEntities()
            : base("server=127.0.0.1;database=eclaimlinkportal;uid=root;password=123456;")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            //throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<clinician> clinicians { get; set; }
        public virtual DbSet<codingset> codingsets { get; set; }
        public virtual DbSet<course> courses { get; set; }
        public virtual DbSet<facilities_allowed_training> facilities_allowed_training { get; set; }
        public virtual DbSet<facility> facilities { get; set; }
        public virtual DbSet<log> logs { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<session> sessions { get; set; }
        public virtual DbSet<ticket> tickets { get; set; }
        public virtual DbSet<ticketcategory> ticketcategories { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<userrole> userroles { get; set; }
        public virtual DbSet<usersession> usersessions { get; set; }
    }
}
