//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACPModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class log
    {
        public long id { get; set; }
        public Nullable<int> applicationid { get; set; }
        public string action { get; set; }
        public Nullable<short> status { get; set; }
        public string details { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public string @params { get; set; }
    }
}
