//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACPModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("ticket")]
    public partial class ticket
    {
        public int id { get; set; }
        [ForeignKey("user")]
        public int createdby { get; set; }
        public Nullable<int> closedby { get; set; }
        public Nullable<System.DateTime> createdat { get; set; }
        public Nullable<System.DateTime> closedat { get; set; }
        public Nullable<System.DateTime> lastupdate { get; set; }
        public string referenceno { get; set; }
        [ForeignKey("ticketcategory")]
        public Nullable<int> categoryid { get; set; }
        public Nullable<short> severity { get; set; }
        public string title { get; set; }
        public string details { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string attachment { get; set; }
        public Nullable<short> status { get; set; }
        public string CloseDetails { get; set; }
    
        public virtual ticketcategory ticketcategory { get; set; }
        public virtual user user { get; set; }
    }
}
