//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACPModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("usersession")]
    public partial class usersession
    {
        public int Id { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<int> sessionId { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string Occupation_Profession { get; set; }
    
        public virtual session session { get; set; }
        public virtual user user { get; set; }
    }
}
